-- Active: 1691795774566@@127.0.0.1@3306@nba_stats
/* 
MYSQL DB
sudo mysql -uroot < init.sql
*/

-- CREATE USER 'auth_user'@'localhost' IDENTIFIED BY 'Aauth123';

-- CREATE DATABASE nba_stats;

GRANT ALL PRIVILEGES ON nba_stats.* TO 'auth_user'@'localhost';

USE nba_stats;


CREATE TABLE arenas (
    ARENA_ID INT AUTO_INCREMENT PRIMARY KEY,
    ARENA_NAME VARCHAR(100) NOT NULL UNIQUE,
    ARENACAPACITY INT
);

CREATE TABLE teams (
    TEAM_ID INT PRIMARY KEY,
    LEAGUE_ID INT,
    MIN_YEAR INT,
    MAX_YEAR INT,
    ABBREVIATION VARCHAR(5),
    NICKNAME VARCHAR(50),
    YEARFOUNDED INT,
    CITY VARCHAR(50),
    ARENA_ID INT,
    FOREIGN KEY(ARENA_ID) REFERENCES arenas(ARENA_ID)
);

CREATE TABLE team_staff (
    TEAM_ID INT,
    OWNER VARCHAR(100),
    GENERALMANAGER VARCHAR(100),
    HEADCOACH VARCHAR(100),
    DLEAGUEAFFILIATION VARCHAR(100),
    FOREIGN KEY(TEAM_ID) REFERENCES teams(TEAM_ID)
);

CREATE TABLE players (
    PLAYER_ID INT PRIMARY KEY,
    PLAYER_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE player_team_associations (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID INT,
    TEAM_ID INT,
    SEASON INT,
    FOREIGN KEY (PLAYER_ID) REFERENCES players(PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES teams(TEAM_ID)
);

CREATE TABLE games (
    GAME_ID INT PRIMARY KEY,
    GAME_DATE_EST DATE,
    GAME_STATUS_TEXT VARCHAR(50),
    SEASON INT,
    HOME_TEAM_WINS BOOLEAN
);

CREATE TABLE team_stats (
    GAME_ID INT,
    TEAM_ID INT,
    HOME_TEAM_OR_AWAY VARCHAR(50),
    PTS FLOAT,
    FG_PCT FLOAT,
    FT_PCT FLOAT,
    FG3_PCT FLOAT,
    AST FLOAT,
    REB FLOAT,
    FOREIGN KEY(GAME_ID) REFERENCES games(GAME_ID),
    FOREIGN KEY(TEAM_ID) REFERENCES teams(TEAM_ID)
);

CREATE TABLE game_details (
    GAME_ID INT,
    PLAYER_ID INT,
    START_POSITION VARCHAR(5),
    COMMENT TEXT,
    MIN VARCHAR(6),
    FGM FLOAT,
    FGA FLOAT,
    FG_PCT FLOAT,
    FG3M FLOAT,
    FG3A FLOAT,
    FG3_PCT FLOAT,
    FTM FLOAT,
    FTA FLOAT,
    FT_PCT FLOAT,
    OREB FLOAT,
    DREB FLOAT,
    REB FLOAT,
    AST FLOAT,
    STL FLOAT,
    BLK FLOAT,
    TO_ FLOAT,
    PF FLOAT,
    PTS FLOAT,
    PLUS_MINUS FLOAT,
    FOREIGN KEY(GAME_ID) REFERENCES games(GAME_ID),
    FOREIGN KEY(PLAYER_ID) REFERENCES players(PLAYER_ID)
);

CREATE TABLE ranking (
    TEAM_ID INT,
    LEAGUE_ID INT,
    SEASON_ID INT,
    STANDINGSDATE DATE,
    CONFERENCE VARCHAR(5),
    TEAM VARCHAR(50),
    G INT,
    W INT,
    L INT,
    W_PCT FLOAT,
    HOME_RECORD VARCHAR(10),
    ROAD_RECORD VARCHAR(10),
    RETURNTOPLAY VARCHAR(10),
    FOREIGN KEY(TEAM_ID) REFERENCES teams(TEAM_ID)
);
